# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20150903_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='time_to',
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 43, 40, 734525), verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
    ]
