# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170820_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(choices=[('other', 'Other'), ('camp', 'Camp'), ('celebration', 'Celebration'), ('competition', 'Competition'), ('meeting', 'Meeting')], default=('other', 'Other'), max_length=32),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 15, 58, 16, 519725), verbose_name='Start'),
        ),
    ]
