# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170822_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 15, 59, 16, 408606), verbose_name='Start'),
        ),
    ]
