# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170826_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 27, 18, 8, 19, 528710), verbose_name='Start'),
        ),
    ]
