# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20170826_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 12, 54, 36, 829403), verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(choices=[('other', 'Other'), ('camp', 'Camp'), ('celebration', 'Celebration'), ('competition', 'Competition'), ('fundraiser', 'Fundraiser'), ('meeting', 'Meeting')], default=('other', 'Other'), max_length=32),
        ),
    ]
