# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-13 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20180827_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 14, 27, 9, 860729), verbose_name='Start'),
        ),
    ]
