# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20191013_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 20, 37, 57, 315871), verbose_name='Start'),
        ),
    ]
