# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-15 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20191014_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 0, 39, 3, 652977), verbose_name='Start'),
        ),
    ]
