# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-15 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20191015_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 17, 20, 1, 375960), verbose_name='Start'),
        ),
    ]
