# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpage',
            name='payment_amount',
            field=models.TextField(default='0', verbose_name='Payment Amount'),
        ),
        migrations.AddField(
            model_name='paymentpage',
            name='payment_description',
            field=models.TextField(default='', verbose_name='Payment Description'),
        ),
    ]
