# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170812_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpage',
            name='payment_amount',
            field=models.TextField(default='0', help_text='Please use the following format: XX.XX, for example: use 21.00 for $21 dolars.', verbose_name='Payment Amount'),
        ),
    ]
