# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20170812_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpage',
            name='payment_amount',
            field=models.TextField(default='0', help_text='Please use full amount without any periods, for example: use 21.00 for $21 dollars.', verbose_name='Payment Amount'),
        ),
    ]
