# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20170817_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpage',
            name='payment_amount',
            field=models.TextField(blank=True, help_text='Please use full amount without any periods, for example: use 2100 for $21 dollars.', verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='paymentpage',
            name='payment_description',
            field=models.TextField(blank=True, verbose_name='Payment Description'),
        ),
    ]
