# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20170819_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpage',
            name='payment_amount',
            field=models.TextField(blank=True, help_text='Optional: Used to set a required payment amount. Must use full amount with cents and no dollar sign, for example use 21.00 for $21 dollars.', verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='paymentpage',
            name='payment_description',
            field=models.TextField(default='Synchro Online Payment', help_text='The payment description that will show up for the bill.', verbose_name='Payment Description'),
        ),
    ]
