# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20170819_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpage',
            name='payment_description',
            field=models.TextField(default='Synchronized Swimming Payment', help_text='The payment description that will show up for the bill.', verbose_name='Payment Description'),
        ),
    ]
